using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using static HPP.GlobalEnums;

namespace HPP.Grid
{
    /// <summary>
    /// GridItem generated by Controller
    /// </summary>
    /// 

    public class GridNode : MonoBehaviour
    {
        [SerializeField] GridColourPallete m_NeutralPallete;
        [SerializeField] GridColourPallete m_UAColourPallete;
        [SerializeField] GridColourPallete m_UBColourPallete;
        [SerializeField] MeshRenderer m_GridNodeMeshRenderer;

        public enum ColourVariant { Variant0, Variant1}

        [SerializeField] private UniverseType m_UniverseType;
        [SerializeField] private ColourVariant m_ColourVariant;

        public UniverseType GridUniverseType => m_UniverseType;
        public ColourVariant GridColourVariant => m_ColourVariant;

        [SerializeField] private int m_XRef;
        [SerializeField] private int m_YRef;
        private GridNode m_PreviouslyTravelledNode = null;

        public AdjacentGridNodes AdjacentGridNodes;

        public int XRef => m_XRef;
        public int YRef => m_YRef;

        private GridColourPallete GetColourPallete(UniverseType universeType)
        {
            switch (universeType)
            {
                case UniverseType.Neutral:
                    return m_NeutralPallete;
                case UniverseType.UniverseA:
                    return m_UAColourPallete;
                case UniverseType.UniverseB:
                    return m_UBColourPallete;
                default:
                    return null;
            }
        }

        private Material GetBaseMaterial(ColourVariant colourVariant, UniverseType universeType)
        {
            GridColourPallete colourPallete = GetColourPallete(universeType);
            return colourVariant == ColourVariant.Variant0 ?
                colourPallete.BaseMaterial0 :
                colourPallete.BaseMaterial1;
        }

        private Color GetBaseColour(ColourVariant colourVariant, UniverseType universeType)
        {
            GridColourPallete colourPallete = GetColourPallete(universeType);
            return colourVariant == ColourVariant.Variant0 ?
                colourPallete.BaseColour0 :
                colourPallete.BaseColour1;
        }

        private Color GetHighlightColour(ColourVariant colourVariant, UniverseType universeType)
        {
            GridColourPallete colourPallete = GetColourPallete(universeType);
            return colourVariant == ColourVariant.Variant0 ?
                colourPallete.HighlightColour0 :
                colourPallete.HighlightColour1;
        }

        public GridNode GetPreviouslyTravelledNode()
        {
            return m_PreviouslyTravelledNode;
        }

        public void SetListRefs(int xRef, int yRef)
        {
            m_XRef = xRef;
            m_YRef = yRef;
        }

        public void SetGridNodeProperties(ColourVariant colourVariant, UniverseType universeType, InteractionType interactionType = InteractionType.DefaultState)
        {
            m_GridNodeMeshRenderer.material = GetBaseMaterial(colourVariant, universeType);
            if (interactionType != InteractionType.Null)
            {
                SetInteractiveStatus(interactionType);
            }
            m_UniverseType = universeType;
            m_ColourVariant = colourVariant;
        }

        public void SetGridNodeProperties(bool isBaseColour0, UniverseType universeType, InteractionType interactionType = InteractionType.DefaultState)
        {
            SetGridNodeProperties(isBaseColour0 ? ColourVariant.Variant0 : ColourVariant.Variant1, universeType, interactionType);
        }

        public void SetInteractiveStatus(InteractionType interactionType)
        {
            switch (interactionType)
            {
                case InteractionType.DefaultState:
                    m_GridNodeMeshRenderer.material.color = GetBaseColour(m_ColourVariant, m_UniverseType);
                    break;
                case InteractionType.BasicTileHit:
                    //break;
                case InteractionType.Interactable:
                    //break;
                case InteractionType.Reclaimable:
                    m_GridNodeMeshRenderer.material.color = GetHighlightColour(m_ColourVariant, m_UniverseType);
                    break;
            }
        }

        public void SetUniverseType(UniverseType universeType)
        {
            SetGridNodeProperties(m_ColourVariant, universeType);
        }
        
        public void SetColourVariant(ColourVariant colourVariant)
        {
            SetGridNodeProperties(colourVariant, m_UniverseType);
        }    

        public void SetColourVariant(bool isBaseColour0)
        {
            SetColourVariant(isBaseColour0 ? ColourVariant.Variant0 : ColourVariant.Variant1);
        }

        public void SetLocalPosition(Vector2 newPosition)
        {
            SetLocalPosition(new Vector3(newPosition.x, 0, newPosition.y));
        }

        public void SetLocalPosition(float x, float y)
        {
            SetLocalPosition(new Vector2(x, y));
        }

        public void SetLocalPosition(Vector3 newPosition)
        {
            transform.localPosition = newPosition;
        }

        public List<GridNode> GetAdjacentNodes(bool useDiagonal = true, bool onlyMyUniverse = false)
        { 
            List<GridNode> adjacentGridNodes = new List<GridNode>();
            if (AdjacentGridNodes.NorthGN != null && (!onlyMyUniverse || (onlyMyUniverse && AdjacentGridNodes.NorthGN.m_UniverseType == m_UniverseType)))
            {
                adjacentGridNodes.Add(AdjacentGridNodes.NorthGN);
            }
            if (AdjacentGridNodes.SouthGN != null && (!onlyMyUniverse || (onlyMyUniverse && AdjacentGridNodes.SouthGN.m_UniverseType == m_UniverseType)))
            {
                adjacentGridNodes.Add(AdjacentGridNodes.SouthGN);
            }
            if (AdjacentGridNodes.EastGN != null && (!onlyMyUniverse || (onlyMyUniverse && AdjacentGridNodes.EastGN.m_UniverseType == m_UniverseType)))
            {
                adjacentGridNodes.Add(AdjacentGridNodes.EastGN);
            }
            if (AdjacentGridNodes.WestGN != null && (!onlyMyUniverse || (onlyMyUniverse && AdjacentGridNodes.WestGN.m_UniverseType == m_UniverseType)))
            {
                adjacentGridNodes.Add(AdjacentGridNodes.WestGN);
            }

            if (useDiagonal)
            {
                if (AdjacentGridNodes.NorthEastGN != null && (!onlyMyUniverse || (onlyMyUniverse && AdjacentGridNodes.NorthEastGN.m_UniverseType == m_UniverseType)))
                {
                    adjacentGridNodes.Add(AdjacentGridNodes.NorthEastGN);
                }
                if (AdjacentGridNodes.SouthEastGN != null &&  (!onlyMyUniverse || (onlyMyUniverse && AdjacentGridNodes.SouthEastGN.m_UniverseType == m_UniverseType)))
                {
                    adjacentGridNodes.Add(AdjacentGridNodes.SouthEastGN);
                }
                if (AdjacentGridNodes.SouthWestGN != null && (!onlyMyUniverse || (onlyMyUniverse && AdjacentGridNodes.SouthWestGN.m_UniverseType == m_UniverseType)))
                {
                    adjacentGridNodes.Add(AdjacentGridNodes.SouthWestGN);
                }
                if (AdjacentGridNodes.NorthWestGN != null && (!onlyMyUniverse || (onlyMyUniverse && AdjacentGridNodes.NorthWestGN.m_UniverseType == m_UniverseType)))
                {
                    adjacentGridNodes.Add(AdjacentGridNodes.NorthWestGN);
                }
            }

            return adjacentGridNodes;
        }

    }

    [System.Serializable]
    public struct AdjacentGridNodes
    {
        public GridNode NorthGN;
        public GridNode SouthGN;
        public GridNode EastGN;
        public GridNode WestGN;

        public GridNode NorthEastGN;
        public GridNode SouthEastGN;
        public GridNode SouthWestGN;
        public GridNode NorthWestGN;
    }

}

