using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace HPP.Grid
{
    /// <summary>
    /// GridItem generated by Controller
    /// </summary>
    /// 

    public class GridItem : MonoBehaviour
    {
        [SerializeField] GridColourPallete m_NeutralPallete;
        [SerializeField] GridColourPallete m_UAColourPallete;
        [SerializeField] GridColourPallete m_UBColourPallete;
        [SerializeField] MeshRenderer m_GridItemMeshRenderer;
        [SerializeField] MeshRenderer m_HoverRenderer;

        public enum UniverseType { Neutral, UniverseA, UniverseB}
        public enum ColourVariant { Variant0, Variant1}

        private UniverseType m_UniverseType;
        private ColourVariant m_ColourVariant;

        public UniverseType GridUniverseType => m_UniverseType;
        public ColourVariant GridColourVariant => m_ColourVariant;

        private int m_XRef, m_YRef;

        public int XRef => m_XRef;
        public int YRef => m_YRef;


        private void Awake()
        {
            m_HoverRenderer.enabled = false;
        }

        private GridColourPallete GetColourPallete(UniverseType universeType)
        {
            switch (universeType)
            {
                case UniverseType.Neutral:
                    return m_NeutralPallete;
                case UniverseType.UniverseA:
                    return m_UAColourPallete;
                case UniverseType.UniverseB:
                    return m_UBColourPallete;
                default:
                    return null;
            }
        }

        public void SetListRefs(int xRef, int yRef)
        {
            m_XRef = xRef;
            m_YRef = yRef;
        }

        public void SetGridItemProperties(ColourVariant colourVariant, UniverseType universeType)
        {
            GridColourPallete colourPallete = GetColourPallete(universeType);
            m_GridItemMeshRenderer.material =
                colourVariant == ColourVariant.Variant0 ?
                colourPallete.BaseMaterial0 :
                colourPallete.BaseMaterial1;

            m_UniverseType = universeType;
            m_ColourVariant = colourVariant;
        }

        public void SetGridItemProperties(bool isBaseColour0, UniverseType universeType)
        {
            SetGridItemProperties(isBaseColour0 ? ColourVariant.Variant0 : ColourVariant.Variant1, universeType);
        }

        public void SetUniverseType(UniverseType universeType)
        {
            SetGridItemProperties(m_ColourVariant, universeType);
        }
        
        public void SetColourVariant(ColourVariant colourVariant)
        {
            SetGridItemProperties(colourVariant, m_UniverseType);
        }    

        public void SetColourVariant(bool isBaseColour0)
        {
            SetColourVariant(isBaseColour0 ? ColourVariant.Variant0 : ColourVariant.Variant1);
        }

        public void SetLocalPosition(Vector2 newPosition)
        {
            SetLocalPosition(new Vector3(newPosition.x, 0, newPosition.y));
        }

        public void SetLocalPosition(float x, float y)
        {
            SetLocalPosition(new Vector2(x, y));
        }

        public void SetLocalPosition(Vector3 newPosition)
        {
            transform.localPosition = newPosition;
        }
    }
}
